drop trigger if exists trg_triggers_webhook_gate on public.workflow_triggers;
drop function if exists public.enforce_webhook_trigger_gate();
drop trigger if exists trg_steps_sensitive_gate on public.workflow_steps;
drop function if exists public.enforce_sensitive_step_gate();
drop trigger if exists trg_workflows_touch on public.workflows;
drop function if exists public.touch_updated_at();
drop function if exists public.current_org_role(uuid, uuid);
drop view if exists public.org_usage_stats;
drop table if exists public.leads;
drop table if exists public.step_runs;
drop table if exists public.workflow_runs;
drop table if exists public.workflow_triggers;
drop table if exists public.workflow_steps;
drop table if exists public.workflows;
drop table if exists public.org_members;
drop table if exists public.organizations;
drop type if exists step_run_status;
drop type if exists run_status;
drop type if exists trigger_type;
drop type if exists step_type;
drop type if exists org_role;
